version: '3.8'

networks:
  e-site:
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

services:
  backend:
    container_name: e-site-backend
    build:
      context: backend
      args:
        BACKEND_DIR: ${BACKEND_DIR}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend/store/:${BACKEND_DIR}/store/
    networks:
      e-site:
        ipv4_address: 10.10.1.1
    ports: # host:container
      - "10100:10100"

  frontend:
    image: caddy:2.6.2
    container_name: e-site-frontend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/frontend/dist:/root/dist
      - ${PWD}/frontend/caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      e-site:
        ipv4_address: 10.10.2.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend