"""Rename field 

Revision ID: c9cbbea2040e
Revises: 907a96e490e7
Create Date: 2022-12-28 16:09:51.991112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cbbea2040e'
down_revision = '907a96e490e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('display', sa.Boolean(), nullable=True))
    op.drop_column('notes', 'is_show')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_show', sa.BOOLEAN(), nullable=True))
    op.drop_column('notes', 'display')
    # ### end Alembic commands ###
